### ISSUE TITLE
windows needs to install bzip2 first?

### ISSUE THREAD

**Issue by lzytaro** [sanbornm/go-selfupdate#59]
command in powershell:
```
PS E:\go_project\src\test_selfupdate\go-selfupdate\example> .\go-selfupdate.exe hello-updater.exe 1.3
panic: exec: "bzip2": executable file not found in %PATH%

goroutine 1 [running]:
main.createUpdate({0xc0000b0030, 0x11}, {0x3b49a2, 0xd})
        E:/go_project/src/test_selfupdate/go-selfupdate/cmd/go-selfupdate/main.go:121 +0xa6b
main.main()
        E:/go_project/src/test_selfupdate/go-selfupdate/cmd/go-selfupdate/main.go:182 +0x29a
```

**Comment by sanbornm** [comment]
Dang, I didn't realize it shelled out to bzip2. Looks like it should probably be fixed upstream here: https://github.com/kr/binarydist/issues/5 Fix: https://github.com/kr/binarydist/pull/9/files or install bzip2 on Windows.
